[tox]
requires = tox>=4.21
env_list = pre-commit,py{310,311,312,313,314,315}
skip_missing_interpreters = True

[testenv:pre-commit]
skip_install = True
dependency_groups = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure --color=always

[testenv:py{,310,311,312,313,314,315}]
skip_install = True
dependency_groups = test
commands =
    uv pip install --find-links=wheelhouse --no-index --only-binary :all: --pre std-nslog
    python -m pytest {posargs:-v tests}
